apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tag-validation-webhook-clusterrole
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tag-validation-webhook-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: tag-validation-webhook-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: tag-validation-webhook-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tag-validation-webhook-sa
  namespace: default
